### PR TITLE
Update Phony gem to 2.16.1

### PR DESCRIPTION
**Pull request by yamanaltereh**

### CODE REVIEW

**Comment by czhc** [comment]
@yamanaltereh will need to merge [this](https://github.com/kaodim/phony_rails/pull/3) to master first to setup circleci

**Comment by yamanaltereh** [comment]
@czhc yes waiting you to approve it 👍

**Comment by czhc** [comment]
@yamanaltereh i mean need to merge [this](https://github.com/kaodim/phony_rails/pull/3)

**Comment by yamanaltereh** [comment]
@czhc I see, okay

**Comment by yamanaltereh** [comment]
@czhc it's ready to merge, can I merge it?

**Review by czhc — APPROVED** [review]

**Pull request merged**
